import { createApp } from "vue";
import App from "./App.vue";
import "./assets/base.css";
import router from "./router/index";
import store from "./store";
import mitt from "mitt";
const app = createApp(App);
app.use(router);
app.use(store);
app.config.globalProperties.mittBus = new mitt();
app.mount("#app");
